[project]
name = "bingxtg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bingx>=0.0.74",
    "cryptography>=45.0.5",
    "dataframe-image==0.2.2",
    "loguru==0.7.2",
    "numpy==1.26.2",
    "pandas==2.1.3",
    "py-bingx>=0.4",
    "pyrogram==2.0.106",
    "requests==2.31.0",
    "tgcrypto>=1.2.5",
]
